### ISSUE TITLE
Missing instance of FromSQLValue Instant

### ISSUE THREAD

**Issue by dwhitney** [rightfold/purescript-postgresql-client#10]
perhaps there is an obvious reason this is missing? Or just overlooked? the ToSQLValue for it exists.

**Comment by dwhitney** [comment]
I'm happy to make a PR if it's just overlooked

**Comment by paluh** [comment]
@dwhitney Please do if you are still interested!

P.S. Sorry for late response!

**Comment by paluh** [comment]
Fixed bb493e59832a1ce0594b278112ea49477e0a276c
