### ISSUE TITLE
Drop scary message from README

### ISSUE THREAD

**Issue by paluh** [rightfold/purescript-postgresql-client#18]
I've started [porting Selda](https://github.com/paluh/purescript-little-selda) to PureScript and want to use this library extensively as a base communication layer with postgresql. I think that I can dedicate more time to maintain it now.
@rightfold Can I drop this warning from README? Should I add info about me as maintainer to the README?

**Comment by rightfold** [comment]
Yeah go ahead!

**Comment by paluh** [comment]
Thanks! Done.

I wonder:

Can I ask you questions in case of any doubts regarding further design/implementation decisions or you just don't want to here about this library any more?

**Comment by rightfold** [comment]
Fixed. I don't really mind what happens to this library, but I don't mind talking about PostgreSQL clients either. The better the library, the better for the PostgreSQL and PureScript communities.
