### ISSUE TITLE
Does newPool need to be Aff?

### ISSUE THREAD

**Issue by rndnoise** [rightfold/purescript-postgresql-client#31]
This may be more trouble than it's worth, but I wish `newPool` returned simply `Effect Pool` rather than `Aff Pool` (or that there were two functions). This seems necessary in some cases, for instance to initialize the Pool a single time before passing it to router with `HTTPure`:

```
import HTTPure as H
import Database.PostgreSQL as P

main :: Effect Unit
main = do
  pool <- P.newPool P.defaultPoolConfiguration -- type error: Aff Pool vs Effect Pool
  H.serve 8080 (router pool) (\_ -> pure unit)

router :: P.Pool -> H.Request -> Aff H.Response
router pool { body, method } = do
  P.withConnection pool \c -> do
    -- ...
    H.ok "..."
```

The workaround I'm using is to pass `PoolConfiguration` to `router` and calling `newPool` inside, but I'm not sure if that does what I want. It seems this would result in a separate pool for each request, rather than a single one shared among requests. Looking at the `pg-pool` library, it seems that `pg.Pool(...)` calls a constructor and doesn't return a promise.

If you agree and prefer to have someone submit a PR, I would be happy to submit one. Though I think most of the work is deciding whether to change `newPool`'s return type, or to create a new function.

**Comment by paluh** [comment]
Hi @rndnoise,

Good catch! I see that we can have `newPool` just in `Effect` by droping `liftEffect` from it. I'm not sure why we are wrapping it in `Aff` ;-)
I can incorporate this change myself because we are expecting a new release this week but if you want to play with the lib you are more the welcome to provide a PR :-)

**Comment by rndnoise** [comment]
Great! I'll look forward to the release :-)

**Comment by paluh** [comment]
This is done on `master` so I'm adding this to `v3.0.0` milestone and closing this issue :-)
