### ISSUE TITLE
Update dependencies so code compiles on 0.13.2 and with latest packages

### ISSUE THREAD

**Issue by JordanMartinez** [rightfold/purescript-postgresql-client#35]
I initially tried to use this in a Spago project and ran into some issues on the `0.13.2` PureScript release.
One of the issues was due to `typelevel-prelude` having a name clash with `Row.Cons`. The second was that `Foreign.Internal (readObject)` was moved to `Foreign.Generic.Internal (readObject)` [see Pursuit](https://pursuit.purescript.org/packages/purescript-foreign-generic/10.0.0/docs/Foreign.Generic.Internal#v:readObject)

**Comment by paluh** [comment]
Hi,

thanks for detailed report @JordanMartinez. I hope I find some time before my holiday to bump may local `purs` version and provide and test a fix. If not this will wait probably till second half of August :-(

**Comment by JordanMartinez** [comment]
No worries! I've already forked this repo and converted it to Spago and made it compile. So, I can still use it.

**Comment by paluh** [comment]
Would you be so kind and revert this change on your branch so I can merge it directly from your fork (you can force push to your repo too)?

**Comment by JordanMartinez** [comment]
I see two ways of interpreting your request. Could you clarify which you're asking me to do?

I converted the code to Spago because I wouldn't have to deal with ranges in dependencies. So, are you asking me to revert those changes so that the code is compileable once the dependencies are updated, but you will figure out which dependency ranges are needed to make it work (and still work if those same libraries have future non-breaking changes)? Or are you asking me to both revert and figure out the dependency ranges? Of the two, I'd only be willing to the first.

**Comment by paluh** [comment]
No, no - I want to leave `spago` integration which you have done this should ease developement flow and dependency management (generation of `bower.json`). I've just asked you kindly to revert this change related to literate test removal :-) Or you can leave it and I will bring back this test after merge I hope tomorrow.

**Comment by JordanMartinez** [comment]
Oh! Ok. Yeah, see current `master` branch now in my fork. I've removed the `lit test removal` commit.

**Comment by paluh** [comment]
I've merged your changes. Thanks a lot @JordanMartinez !

**Comment by paluh** [comment]
P.S.
I've created `v3.0.0` milestone to inform users about possible changes in the next release: 
https://github.com/rightfold/purescript-postgresql-client/milestone/1
I hope you find it useful ;-)
