### ISSUE TITLE
Consider transforming `PG` monad stack into mtl style `class`.

### ISSUE THREAD

**Issue by paluh** [rightfold/purescript-postgresql-client#36]
We can probably provide polymorphic version of `PG` instead of concrete stack - something like this should be sufficient:

```purescript
class (MonadAff m, MonadError PGError m) <= MonadPG m
```

**Comment by JordanMartinez** [comment]
If we hard-code the `e` type to `PGError`, won't that limit other error types from being used in a computation? I'm not sure whether one would do such a thing, but I thought I'd bring it up.

**Comment by paluh** [comment]
> If we hard-code the e type to PGError, won't that limit other error types from being used in a computation?

This base monad should be hoisted into application stack by usage `withExceptT`. We are not able to avoid some form of hoisting I think. The problem is that current model with hardcoded `ExceptT` seems to be hard to hoist in real world scenarios.

**Comment by paluh** [comment]
https://github.com/rightfold/purescript-postgresql-client/pull/41
